export const FETCH_POPULAR_START = 'FETCH_POPULAR_START';
export const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS';
export const FETCH_POPULAR_FAIL = 'FETCH_POPULAR_FAIL';

export const FETCH_SEARCH_START = 'FETCH_SEARCH_START';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL';

export const FETCH_PHOTO_START = 'FETCH_PHOTO_START';
export const FETCH_PHOTO_SUCCESS = 'FETCH_PHOTO_SUCCESS';
export const FETCH_PHOTO_FAIL = 'FETCH_PHOTO_FAIL';

export const FETCH_SINGLE_IMAGE = 'FETCH_SINGLE_IMAGE';

export const FETCH_CART_START = 'FETCH_CART_START';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAIL = 'FETCH_CART_FAIL';

export const FETCH_FAVORITES_START = 'FETCH_FAVORITES_START';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_FAIL = 'FETCH_FAVORITES_FAIL';

export const ADD_FAVORITE_START = 'ADD_FAVORITE_START';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_FAIL = 'ADD_FAVORITE_FAIL';

export const DELETE_FAVORITE_START = 'DELETE_FAVORITE_START';
export const DELETE_FAVORITE_SUCCESS = 'DELETE_FAVORITE_SUCCESS';
export const DELETE_FAVORITE_FAIL = 'DELETE_FAVORITE_FAIL';

export const ADD_CART_START = 'ADD_CART_START';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_FAIL = 'ADD_CART_FAIL';

export const DELETE_CART_START = 'DELETE_CART_START';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
export const DELETE_CART_FAIL = 'DELETE_CART_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const ADD_COMPARE_START = 'ADD_COMPARE_START';
export const ADD_COMPARE_SUCCESS = 'ADD_COMPARE_SUCCESS';
export const ADD_COMPARE_FAIL = 'ADD_COMPARE_FAIL';

export const DELETE_COMPARE_START = 'DELETE_COMPARE_START';
export const DELETE_COMPARE_SUCCESS = 'DELETE_COMPARE_SUCCESS';
export const DELETE_COMPARE_FAIL = 'DELETE_COMPARE_FAIL';

export const FETCH_COMPARE_START = 'FETCH_COMPARE_START';
export const FETCH_COMPARE_SUCCESS = 'FETCH_COMPARE_SUCCESS';
export const FETCH_COMPARE_FAIL = 'FETCH_COMPARE_FAIL';

export const PURCHASE_PRODUCT_START = 'PURCHASE_PRODUCT_START';
export const PURCHASE_PRODUCT_SUCCESS = 'PURCHASE_PRODUCT_SUCCESS';
export const PURCHASE_PRODUCT_FAIL = 'PURCHASE_PRODUCT_FAIL';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';

export const PURCHASE_INIT = 'PURCHASE_INIT';